;(function($){
	$(".howdianliang").on("click",function(){		
		$(".mengceng").show();
		$(".mengceng").css("opacity","0.7");
		$(".CBAxunzhang").show();
	})
	$(".closeBtn").on("click",function(){
		$(".mengceng").hide();	 
		$(".CBAxunzhang").hide();
		$(".qiandaoxiangqing").hide();
	})
	$(".iknow").on("click",function(){
		$(".mengceng").hide();	 
		$(".CBAxunzhang").hide();
		$(".qiandaoxiangqing").hide();
	})
	$(".mengceng").on("click",function(){
		$(".mengceng").hide();	 
		$(".CBAxunzhang").hide();
		$(".qiandaoxiangqing").hide();
	})	
	$("#jifen").on("click",function(){
		alert("提示")
		/*location.href="../jifen/index.html"*/
	})
	$("#jinbi").on("click",function(){
		location.href="../jinbi/index.html"
	})
	$("#maiqiupiao").on("click",function(){
		alert("跳入微信页面")
	})
	$("#jifenshop").on("click",function(){
		alert("跳入积分商城")
	})
	$("#mineDingdan").on("click",function(){
		location.href="../mydingdan/index.html"
	})
	$("#boundmobile").on("click",function(){
		location.href="../boundmobile/index.html"
	})
	
	/*$("#adressBtn").on("click",function(){
		location.href="../boundmobile/index.html"
	})*/
	$("#kanjihousai").on("click",function(){
		location.href="../CBAzhuanshu/index.html"
	})
	$(".qiandao").on("click",function(){
		$(".mengceng").show();
		$(".mengceng").css("opacity","0.7");
		$(".qiandaoxiangqing").show();
	})
 
})(Zepto)